const nonFilteredZones = [
  {order: 1, level: 1, twdgCode: '1', name: 'Europe'},
  {order: 2, level: 2, twdgCode: '10', name: 'Northern Europe'},
  {order: 3, level: 3, twdgCode: 'DEN', name: 'Denmark'},
  {order: 4, level: 3, twdgCode: 'FIN', name: 'Finland'},
  {order: 5, level: 3, twdgCode: 'FOR', name: 'Føroyar'},
  {order: 6, level: 3, twdgCode: 'GRB', name: 'Great Britain'},
  {order: 7, level: 3, twdgCode: 'ICE', name: 'Iceland'},
  {order: 8, level: 3, twdgCode: 'IRE', name: 'Ireland'},
  {order: 9, level: 4, twdgCode: 'IRE-IR', name: 'Ireland'},
  {order: 10, level: 4, twdgCode: 'IRE-NI', name: 'Northern Ireland'},
  {order: 11, level: 3, twdgCode: 'NOR', name: 'Norway'},
  {order: 12, level: 3, twdgCode: 'SVA', name: 'Svalbard'},
  {order: 13, level: 3, twdgCode: 'SWE', name: 'Sweden'},
  {order: 14, level: 2, twdgCode: '11', name: 'Middle Europe'},
  {order: 15, level: 3, twdgCode: 'AUT', name: 'Austria'},
  {order: 16, level: 4, twdgCode: 'AUT-AU', name: 'Austria'},
  {order: 17, level: 4, twdgCode: 'AUT-LI', name: 'Liechtenstein'},
  {order: 18, level: 3, twdgCode: 'BGM', name: 'Belgium'},
  {order: 19, level: 4, twdgCode: 'BGM-BE', name: 'Belgium'},
  {order: 20, level: 4, twdgCode: 'BGM-LU', name: 'Luxembourg'},
  {order: 21, level: 3, twdgCode: 'CZE', name: 'Czechoslovakia'},
  {order: 22, level: 4, twdgCode: 'CZE-CZ', name: 'Czech Republic'},
  {order: 23, level: 4, twdgCode: 'CZE-SL', name: 'Slovakia'},
  {order: 24, level: 3, twdgCode: 'GER', name: 'Germany'},
  {order: 25, level: 3, twdgCode: 'HUN', name: 'Hungary'},
  {order: 26, level: 3, twdgCode: 'NET', name: 'Netherlands'},
  {order: 27, level: 3, twdgCode: 'POL', name: 'Poland'},
  {order: 28, level: 3, twdgCode: 'SWI', name: 'Switzerland'},
  {order: 29, level: 2, twdgCode: '12', name: 'Southwestern Europe'},
  {order: 30, level: 3, twdgCode: 'BAL', name: 'Baleares'},
  {order: 31, level: 3, twdgCode: 'COR', name: 'Corse'},
  {order: 32, level: 3, twdgCode: 'FRA', name: 'France'},
  {order: 33, level: 4, twdgCode: 'FRA-CI', name: 'Channel Is.'},
  {order: 34, level: 4, twdgCode: 'FRA-FR', name: 'France'},
  {order: 35, level: 4, twdgCode: 'FRA-MO', name: 'Monaco'},
  {order: 36, level: 3, twdgCode: 'POR', name: 'Portugal'},
  {order: 37, level: 3, twdgCode: 'SAR', name: 'Sardegna'},
  {order: 38, level: 3, twdgCode: 'SPA', name: 'Spain'},
  {order: 39, level: 4, twdgCode: 'SPA-AN', name: 'Andorra'},
  {order: 40, level: 4, twdgCode: 'SPA-GI', name: 'Gibraltar'},
  {order: 41, level: 4, twdgCode: 'SPA-SP', name: 'Spain'},
  {order: 42, level: 2, twdgCode: '13', name: 'Southeastern Europe'},
  {order: 43, level: 3, twdgCode: 'ALB', name: 'Albania'},
  {order: 44, level: 3, twdgCode: 'BUL', name: 'Bulgaria'},
  {order: 45, level: 3, twdgCode: 'GRC', name: 'Greece'},
  {order: 46, level: 3, twdgCode: 'ITA', name: 'Italy'},
  {order: 47, level: 4, twdgCode: 'ITA-IT', name: 'Italy'},
  {order: 48, level: 4, twdgCode: 'ITA-SM', name: 'San Marino'},
  {order: 49, level: 4, twdgCode: 'ITA-VC', name: 'Vatican City'},
  {order: 50, level: 3, twdgCode: 'KRI', name: 'Kriti'},
  {order: 51, level: 3, twdgCode: 'ROM', name: 'Romania'},
  {order: 52, level: 3, twdgCode: 'SIC', name: 'Sicilia'},
  {order: 53, level: 4, twdgCode: 'SIC-MA', name: 'Malta'},
  {order: 54, level: 4, twdgCode: 'SIC-SI', name: 'Sicilia'},
  {order: 55, level: 3, twdgCode: 'TUE', name: 'Turkey-in-Europe'},
  {order: 56, level: 3, twdgCode: 'YUG', name: 'Yugoslavia'},
  {order: 57, level: 4, twdgCode: 'YUG-BH', name: 'Bosnia- Herzegovina'},
  {order: 58, level: 4, twdgCode: 'YUG-CR', name: 'Croatia'},
  {order: 59, level: 4, twdgCode: 'YUG-KO', name: 'Kosovo'},
  {order: 60, level: 4, twdgCode: 'YUG-MA', name: 'Macedonia'},
  {order: 61, level: 4, twdgCode: 'YUG-MN', name: 'Montenegro'},
  {order: 62, level: 4, twdgCode: 'YUG-SE', name: 'Serbia'},
  {order: 63, level: 4, twdgCode: 'YUG-SL', name: 'Slovenia'},
  {order: 64, level: 2, twdgCode: '14', name: 'Eastern Europe'},
  {order: 65, level: 3, twdgCode: 'BLR', name: 'Belarus'},
  {order: 66, level: 3, twdgCode: 'BLT', name: 'Baltic States'},
  {order: 67, level: 4, twdgCode: 'BLT-ES', name: 'Estonia'},
  {order: 68, level: 4, twdgCode: 'BLT-KA', name: 'Kaliningrad'},
  {order: 69, level: 4, twdgCode: 'BLT-LA', name: 'Latvia'},
  {order: 70, level: 4, twdgCode: 'BLT-LI', name: 'Lithuania'},
  {order: 71, level: 3, twdgCode: 'KRY', name: 'Krym'},
  {order: 72, level: 3, twdgCode: 'RUC', name: 'Central European Russia'},
  {order: 73, level: 3, twdgCode: 'RUE', name: 'East European Russia'},
  {order: 74, level: 3, twdgCode: 'RUN', name: 'North European Russia'},
  {order: 75, level: 3, twdgCode: 'RUS', name: 'South European Russia'},
  {order: 76, level: 3, twdgCode: 'RUW', name: 'Northwest European Russia'},
  {order: 77, level: 3, twdgCode: 'UKR', name: 'Ukraine'},
  {order: 78, level: 4, twdgCode: 'UKR-MO', name: 'Moldova'},
  {order: 79, level: 4, twdgCode: 'UKR-UK', name: 'Ukraine'},
  {order: 80, level: 1, twdgCode: '2', name: 'Africa'},
  {order: 81, level: 2, twdgCode: '20', name: 'Northern Africa'},
  {order: 82, level: 3, twdgCode: 'ALG', name: 'Algeria'},
  {order: 83, level: 3, twdgCode: 'EGY', name: 'Egypt'},
  {order: 84, level: 3, twdgCode: 'LBY', name: 'Libya'},
  {order: 85, level: 3, twdgCode: 'MOR', name: 'Morocco'},
  {order: 86, level: 4, twdgCode: 'MOR-MO', name: 'Morocco'},
  {
    order: 87,
    level: 4,
    twdgCode: 'MOR-SP',
    name: 'Spanish North African Territories'
  },
  {order: 88, level: 3, twdgCode: 'TUN', name: 'Tunisia'},
  {order: 89, level: 3, twdgCode: 'WSA', name: 'Western Sahara'},
  {order: 90, level: 2, twdgCode: '21', name: 'Macaronesia'},
  {order: 91, level: 3, twdgCode: 'AZO', name: 'Azores'},
  {order: 92, level: 3, twdgCode: 'CNY', name: 'Canary Is.'},
  {order: 93, level: 3, twdgCode: 'CVI', name: 'Cape Verde'},
  {order: 94, level: 3, twdgCode: 'MDR', name: 'Madeira'},
  {order: 95, level: 3, twdgCode: 'SEL', name: 'Selvagens'},
  {order: 96, level: 2, twdgCode: '22', name: 'West Tropical Africa'},
  {order: 97, level: 3, twdgCode: 'BEN', name: 'Benin'},
  {order: 98, level: 3, twdgCode: 'BKN', name: 'Burkina'},
  {order: 99, level: 3, twdgCode: 'GAM', name: 'Gambia, The'},
  {order: 100, level: 3, twdgCode: 'GHA', name: 'Ghana'},
  {order: 101, level: 3, twdgCode: 'GNB', name: 'Guinea-Bissau'},
  {order: 102, level: 3, twdgCode: 'GUI', name: 'Guinea'},
  {order: 103, level: 3, twdgCode: 'IVO', name: 'Ivory Coast'},
  {order: 104, level: 3, twdgCode: 'LBR', name: 'Liberia'},
  {order: 105, level: 3, twdgCode: 'MLI', name: 'Mali'},
  {order: 106, level: 3, twdgCode: 'MTN', name: 'Mauritania'},
  {order: 107, level: 3, twdgCode: 'NGA', name: 'Nigeria'},
  {order: 108, level: 3, twdgCode: 'NGR', name: 'Niger'},
  {order: 109, level: 3, twdgCode: 'SEN', name: 'Senegal'},
  {order: 110, level: 3, twdgCode: 'SIE', name: 'Sierra Leone'},
  {order: 111, level: 3, twdgCode: 'TOG', name: 'Togo'},
  {order: 112, level: 2, twdgCode: '23', name: 'West-Central Tropical Africa'},
  {order: 113, level: 3, twdgCode: 'BUR', name: 'Burundi'},
  {order: 114, level: 3, twdgCode: 'CAB', name: 'Cabinda'},
  {order: 115, level: 3, twdgCode: 'CAF', name: 'Central African Republic'},
  {order: 116, level: 3, twdgCode: 'CMN', name: 'Cameroon'},
  {order: 117, level: 3, twdgCode: 'CON', name: 'Congo'},
  {order: 118, level: 3, twdgCode: 'EQG', name: 'Equatorial Guinea'},
  {order: 119, level: 3, twdgCode: 'GAB', name: 'Gabon'},
  {order: 120, level: 3, twdgCode: 'GGI', name: 'Gulf of Guinea Is.'},
  {order: 121, level: 4, twdgCode: 'GGI-AN', name: 'Annobón'},
  {order: 122, level: 4, twdgCode: 'GGI-BI', name: 'Bioko'},
  {order: 123, level: 4, twdgCode: 'GGI-PR', name: 'Príncipe'},
  {order: 124, level: 4, twdgCode: 'GGI-ST', name: 'São Tomé'},
  {order: 125, level: 3, twdgCode: 'RWA', name: 'Rwanda'},
  {order: 126, level: 3, twdgCode: 'ZAI', name: 'Zaire'},
  {order: 127, level: 2, twdgCode: '24', name: 'Northeast Tropical Africa'},
  {order: 128, level: 3, twdgCode: 'CHA', name: 'Chad'},
  {order: 129, level: 3, twdgCode: 'DJI', name: 'Djibouti'},
  {order: 130, level: 3, twdgCode: 'ERI', name: 'Eritrea'},
  {order: 131, level: 3, twdgCode: 'ETH', name: 'Ethiopia'},
  {order: 132, level: 3, twdgCode: 'SOC', name: 'Socotra'},
  {order: 133, level: 3, twdgCode: 'SOM', name: 'Somalia'},
  {order: 134, level: 3, twdgCode: 'SUD', name: 'Sudan'},
  {order: 135, level: 2, twdgCode: '25', name: 'East Tropical Africa'},
  {order: 136, level: 3, twdgCode: 'KEN', name: 'Kenya'},
  {order: 137, level: 3, twdgCode: 'TAN', name: 'Tanzania'},
  {order: 138, level: 3, twdgCode: 'UGA', name: 'Uganda'},
  {order: 139, level: 2, twdgCode: '26', name: 'South Tropical Africa'},
  {order: 140, level: 3, twdgCode: 'ANG', name: 'Angola'},
  {order: 141, level: 3, twdgCode: 'MLW', name: 'Malawi'},
  {order: 142, level: 3, twdgCode: 'MOZ', name: 'Mozambique'},
  {order: 143, level: 3, twdgCode: 'ZAM', name: 'Zambia'},
  {order: 144, level: 3, twdgCode: 'ZIM', name: 'Zimbabwe'},
  {order: 145, level: 2, twdgCode: '27', name: 'Southern Africa'},
  {order: 146, level: 3, twdgCode: 'BOT', name: 'Botswana'},
  {order: 147, level: 3, twdgCode: 'CPP', name: 'Cape Provinces'},
  {order: 148, level: 4, twdgCode: 'CPP-EC', name: 'Eastern Cape Province'},
  {order: 149, level: 4, twdgCode: 'CPP-NC', name: 'Northern Cape Province'},
  {order: 150, level: 4, twdgCode: 'CPP-WC', name: 'Western Cape Province'},
  {order: 151, level: 3, twdgCode: 'CPV', name: 'Caprivi Strip'},
  {order: 152, level: 3, twdgCode: 'LES', name: 'Lesotho'},
  {order: 153, level: 3, twdgCode: 'NAM', name: 'Namibia'},
  {order: 154, level: 3, twdgCode: 'NAT', name: 'KwaZulu-Natal'},
  {order: 155, level: 3, twdgCode: 'OFS', name: 'Free State'},
  {order: 156, level: 3, twdgCode: 'SWZ', name: 'Swaziland'},
  {order: 157, level: 3, twdgCode: 'TVL', name: 'Northern Provinces'},
  {order: 158, level: 4, twdgCode: 'TVL-GA', name: 'Gauteng'},
  {order: 159, level: 4, twdgCode: 'TVL-MP', name: 'Mpumalanga'},
  {order: 160, level: 4, twdgCode: 'TVL-NP', name: 'Northern Province'},
  {order: 161, level: 4, twdgCode: 'TVL-NW', name: 'North-West Province'},
  {order: 162, level: 2, twdgCode: '28', name: 'Middle Atlantic Ocean'},
  {order: 163, level: 3, twdgCode: 'ASC', name: 'Ascension'},
  {order: 164, level: 3, twdgCode: 'STH', name: 'St.Helena'},
  {order: 165, level: 2, twdgCode: '29', name: 'Western Indian Ocean'},
  {order: 166, level: 3, twdgCode: 'ALD', name: 'Aldabra'},
  {order: 167, level: 3, twdgCode: 'CGS', name: 'Chagos Archipelago'},
  {order: 168, level: 3, twdgCode: 'COM', name: 'Comoros'},
  {order: 169, level: 4, twdgCode: 'COM-CO', name: 'Comoros'},
  {order: 170, level: 4, twdgCode: 'COM-MA', name: 'Mayotte'},
  {order: 171, level: 3, twdgCode: 'MAU', name: 'Mauritius'},
  {order: 172, level: 3, twdgCode: 'MCI', name: 'Mozambique Channel Is.'},
  {order: 173, level: 3, twdgCode: 'MDG', name: 'Madagascar'},
  {order: 174, level: 3, twdgCode: 'REU', name: 'Réunion'},
  {order: 175, level: 3, twdgCode: 'ROD', name: 'Rodrigues'},
  {order: 176, level: 3, twdgCode: 'SEY', name: 'Seychelles'},
  {order: 177, level: 1, twdgCode: '3', name: 'Asia-Temperate'},
  {order: 178, level: 2, twdgCode: '30', name: 'Siberia'},
  {order: 179, level: 3, twdgCode: 'ALT', name: 'Altay'},
  {order: 180, level: 3, twdgCode: 'BRY', name: 'Buryatiya'},
  {order: 181, level: 3, twdgCode: 'CTA', name: 'Chita'},
  {order: 182, level: 3, twdgCode: 'IRK', name: 'Irkutsk'},
  {order: 183, level: 3, twdgCode: 'KRA', name: 'Krasnoyarsk'},
  {order: 184, level: 3, twdgCode: 'TVA', name: 'Tuva'},
  {order: 185, level: 3, twdgCode: 'WSB', name: 'West Siberia'},
  {order: 186, level: 3, twdgCode: 'YAK', name: 'Yakutskiya'},
  {order: 187, level: 2, twdgCode: '31', name: 'Russian Far East'},
  {order: 188, level: 3, twdgCode: 'AMU', name: 'Amur'},
  {order: 189, level: 3, twdgCode: 'KAM', name: 'Kamchatka'},
  {order: 190, level: 3, twdgCode: 'KHA', name: 'Khabarovsk'},
  {order: 191, level: 3, twdgCode: 'KUR', name: 'Kuril Is.'},
  {order: 192, level: 3, twdgCode: 'MAG', name: 'Magadan'},
  {order: 193, level: 3, twdgCode: 'PRM', name: 'Primorye'},
  {order: 194, level: 3, twdgCode: 'SAK', name: 'Sakhalin'},
  {order: 195, level: 2, twdgCode: '32', name: 'Middle Asia'},
  {order: 196, level: 3, twdgCode: 'KAZ', name: 'Kazakhstan'},
  {order: 197, level: 3, twdgCode: 'KGZ', name: 'Kirgizistan'},
  {order: 198, level: 3, twdgCode: 'TKM', name: 'Turkmenistan'},
  {order: 199, level: 3, twdgCode: 'TZK', name: 'Tadzhikistan'},
  {order: 200, level: 3, twdgCode: 'UZB', name: 'Uzbekistan'},
  {order: 201, level: 2, twdgCode: '33', name: 'Caucasus'},
  {order: 202, level: 3, twdgCode: 'NCS', name: 'North Caucasus'},
  {order: 203, level: 4, twdgCode: 'NCS-CH', name: 'Chechnya'},
  {order: 204, level: 4, twdgCode: 'NCS-DA', name: 'Dagestan'},
  {order: 205, level: 4, twdgCode: 'NCS-IN', name: 'Ingushetiya'},
  {order: 206, level: 4, twdgCode: 'NCS-KB', name: 'Kabardino-Balkariya'},
  {order: 207, level: 4, twdgCode: 'NCS-KC', name: 'Karacheyevo-Cherkessiya'},
  {order: 208, level: 4, twdgCode: 'NCS-KR', name: 'Krasnodar'},
  {order: 209, level: 4, twdgCode: 'NCS-SO', name: 'Severo-Osetiya'},
  {order: 210, level: 4, twdgCode: 'NCS-ST', name: 'Stavropol'},
  {order: 211, level: 3, twdgCode: 'TCS', name: 'Transcaucasus'},
  {order: 212, level: 4, twdgCode: 'TCS-AB', name: 'Abkhaziya'},
  {order: 213, level: 4, twdgCode: 'TCS-AD', name: 'Adzhariya'},
  {order: 214, level: 4, twdgCode: 'TCS-AR', name: 'Armenia'},
  {order: 215, level: 4, twdgCode: 'TCS-AZ', name: 'Azerbaijan'},
  {order: 216, level: 4, twdgCode: 'TCS-GR', name: 'Gruziya'},
  {order: 217, level: 4, twdgCode: 'TCS-NA', name: 'Nakhichevan'},
  {order: 218, level: 4, twdgCode: 'TCS-NK', name: 'Nagorno Karabakh'},
  {order: 219, level: 2, twdgCode: '34', name: 'Western Asia'},
  {order: 220, level: 3, twdgCode: 'AFG', name: 'Afghanistan'},
  {order: 221, level: 3, twdgCode: 'CYP', name: 'Cyprus'},
  {order: 222, level: 3, twdgCode: 'EAI', name: 'East Aegean Is.'},
  {order: 223, level: 3, twdgCode: 'IRN', name: 'Iran'},
  {order: 224, level: 3, twdgCode: 'IRQ', name: 'Iraq'},
  {order: 225, level: 3, twdgCode: 'LBS', name: 'Lebanon-Syria'},
  {order: 226, level: 4, twdgCode: 'LBS-LB', name: 'Lebanon'},
  {order: 227, level: 4, twdgCode: 'LBS-SY', name: 'Syria'},
  {order: 228, level: 3, twdgCode: 'PAL', name: 'Palestine'},
  {order: 229, level: 4, twdgCode: 'PAL-JO', name: 'Jordan'},
  {order: 230, level: 4, twdgCode: 'PAL-IS', name: 'Israel'},
  {order: 231, level: 3, twdgCode: 'SIN', name: 'Sinai'},
  {order: 232, level: 3, twdgCode: 'TUR', name: 'Turkey'},
  {order: 233, level: 2, twdgCode: '35', name: 'Arabian Peninsula'},
  {order: 234, level: 3, twdgCode: 'GST', name: 'Gulf States'},
  {order: 235, level: 4, twdgCode: 'GST-BA', name: 'Bahrain'},
  {order: 236, level: 4, twdgCode: 'GST-QA', name: 'Qatar'},
  {order: 237, level: 4, twdgCode: 'GST-UA', name: 'United Arab Emirates'},
  {order: 238, level: 3, twdgCode: 'KUW', name: 'Kuwait'},
  {order: 239, level: 3, twdgCode: 'OMA', name: 'Oman'},
  {order: 240, level: 3, twdgCode: 'SAU', name: 'Saudi Arabia'},
  {order: 241, level: 3, twdgCode: 'YEM', name: 'Yemen'},
  {order: 242, level: 4, twdgCode: 'YEM-NY', name: 'North Yemen'},
  {order: 243, level: 4, twdgCode: 'YEM-SY', name: 'South Yemen'},
  {order: 244, level: 2, twdgCode: '36', name: 'China'},
  {order: 245, level: 3, twdgCode: 'CHC', name: 'China South-Central'},
  {order: 246, level: 4, twdgCode: 'CHC-CQ', name: 'Chongqing'},
  {order: 247, level: 4, twdgCode: 'CHC-GZ', name: 'Guizhou'},
  {order: 248, level: 4, twdgCode: 'CHC-HU', name: 'Hubei'},
  {order: 249, level: 4, twdgCode: 'CHC-SC', name: 'Sichuan'},
  {order: 250, level: 4, twdgCode: 'CHC-YN', name: 'Yunnan'},
  {order: 251, level: 3, twdgCode: 'CHH', name: 'Hainan'},
  {order: 252, level: 3, twdgCode: 'CHI', name: 'Inner Mongolia'},
  {order: 253, level: 4, twdgCode: 'CHI-NM', name: 'Nei Mongol'},
  {order: 254, level: 4, twdgCode: 'CHI-NX', name: 'Ningxia'},
  {order: 255, level: 3, twdgCode: 'CHM', name: 'Manchuria'},
  {order: 256, level: 4, twdgCode: 'CHM-HJ', name: 'Heilongjiang'},
  {order: 257, level: 4, twdgCode: 'CHM-JL', name: 'Jilin'},
  {order: 258, level: 4, twdgCode: 'CHM-LN', name: 'Liaoning'},
  {order: 259, level: 3, twdgCode: 'CHN', name: 'China North-Central'},
  {order: 260, level: 4, twdgCode: 'CHN-BJ', name: 'Beijing'},
  {order: 261, level: 4, twdgCode: 'CHN-GS', name: 'Gansu'},
  {order: 262, level: 4, twdgCode: 'CHN-HB', name: 'Hebei'},
  {order: 263, level: 4, twdgCode: 'CHN-SA', name: 'Shaanxi'},
  {order: 264, level: 4, twdgCode: 'CHN-SD', name: 'Shandong'},
  {order: 265, level: 4, twdgCode: 'CHN-SX', name: 'Shanxi'},
  {order: 266, level: 4, twdgCode: 'CHN-TJ', name: 'Tianjin'},
  {order: 267, level: 3, twdgCode: 'CHQ', name: 'Qinghai'},
  {order: 268, level: 3, twdgCode: 'CHS', name: 'China Southeast'},
  {order: 269, level: 4, twdgCode: 'CHS-AH', name: 'Anhui'},
  {order: 270, level: 4, twdgCode: 'CHS-FJ', name: 'Fujian'},
  {order: 271, level: 4, twdgCode: 'CHS-GD', name: 'Guangdong'},
  {order: 272, level: 4, twdgCode: 'CHS-GX', name: 'Guangxi'},
  {order: 273, level: 4, twdgCode: 'CHS-HE', name: 'Henan'},
  {order: 274, level: 4, twdgCode: 'CHS-HK', name: 'Hong Kong'},
  {order: 275, level: 4, twdgCode: 'CHS-HN', name: 'Hunan'},
  {order: 276, level: 4, twdgCode: 'CHS-JS', name: 'Jiangsu'},
  {order: 277, level: 4, twdgCode: 'CHS-JX', name: 'Jiangxi'},
  {order: 278, level: 4, twdgCode: 'CHS-KI', name: 'Kin-Men'},
  {order: 279, level: 4, twdgCode: 'CHS-MA', name: 'Macau'},
  {order: 280, level: 4, twdgCode: 'CHS-MP', name: 'Ma-tsu-Pai-chuan'},
  {order: 281, level: 4, twdgCode: 'CHS-SH', name: 'Shanghai'},
  {order: 282, level: 4, twdgCode: 'CHS-ZJ', name: 'Zhejiang'},
  {order: 283, level: 3, twdgCode: 'CHT', name: 'Tibet'},
  {order: 284, level: 3, twdgCode: 'CHX', name: 'Xinjiang'},
  {order: 285, level: 2, twdgCode: '37', name: 'Mongolia'},
  {order: 286, level: 3, twdgCode: 'MON', name: 'Mongolia'},
  {order: 287, level: 2, twdgCode: '38', name: 'Eastern Asia'},
  {order: 288, level: 3, twdgCode: 'JAP', name: 'Japan'},
  {order: 289, level: 4, twdgCode: 'JAP-HK', name: 'Hokkaido'},
  {order: 290, level: 4, twdgCode: 'JAP-HN', name: 'Honshu'},
  {order: 291, level: 4, twdgCode: 'JAP-KY', name: 'Kyushu'},
  {order: 292, level: 4, twdgCode: 'JAP-SH', name: 'Shikoku'},
  {order: 293, level: 3, twdgCode: 'KOR', name: 'Korea'},
  {order: 294, level: 4, twdgCode: 'KOR-NK', name: 'North Korea'},
  {order: 295, level: 4, twdgCode: 'KOR-SK', name: 'South Korea'},
  {order: 296, level: 3, twdgCode: 'KZN', name: 'Kazan-retto'},
  {order: 297, level: 3, twdgCode: 'NNS', name: 'Nansei-shoto'},
  {order: 298, level: 3, twdgCode: 'OGA', name: 'Ogasawara-shoto'},
  {order: 299, level: 3, twdgCode: 'TAI', name: 'Taiwan'},
  {order: 300, level: 1, twdgCode: '4', name: 'Asia-Tropical'},
  {order: 301, level: 2, twdgCode: '40', name: 'Indian Subcontinent'},
  {order: 302, level: 3, twdgCode: 'ASS', name: 'Assam'},
  {order: 303, level: 4, twdgCode: 'ASS-AS', name: 'Assam'},
  {order: 304, level: 4, twdgCode: 'ASS-MA', name: 'Manipur'},
  {order: 305, level: 4, twdgCode: 'ASS-ME', name: 'Meghalaya'},
  {order: 306, level: 4, twdgCode: 'ASS-MI', name: 'Mizoram'},
  {order: 307, level: 4, twdgCode: 'ASS-NA', name: 'Nagaland'},
  {order: 308, level: 4, twdgCode: 'ASS-TR', name: 'Tripura'},
  {order: 309, level: 3, twdgCode: 'BAN', name: 'Bangladesh'},
  {order: 310, level: 3, twdgCode: 'EHM', name: 'East Himalaya'},
  {order: 311, level: 4, twdgCode: 'EHM-AP', name: 'Arunachal Pradesh'},
  {order: 312, level: 4, twdgCode: 'EHM-BH', name: 'Bhutan'},
  {order: 313, level: 4, twdgCode: 'EHM-DJ', name: 'Darjiling'},
  {order: 314, level: 4, twdgCode: 'EHM-SI', name: 'Sikkim'},
  {order: 315, level: 3, twdgCode: 'IND', name: 'India'},
  {order: 316, level: 4, twdgCode: 'IND-AP', name: 'Andhra Pradesh'},
  {order: 317, level: 4, twdgCode: 'IND-BI', name: 'Bihar'},
  {order: 318, level: 4, twdgCode: 'IND-CH', name: 'Chandigarh'},
  {order: 319, level: 4, twdgCode: 'IND-CT', name: 'Chhattisgarh'},
  {order: 320, level: 4, twdgCode: 'IND-DD', name: 'Dadra-Nagar-Haveli'},
  {order: 321, level: 4, twdgCode: 'IND-DE', name: 'Delhi'},
  {order: 322, level: 4, twdgCode: 'IND-DI', name: 'Diu'},
  {order: 323, level: 4, twdgCode: 'IND-DM', name: 'Daman'},
  {order: 324, level: 4, twdgCode: 'IND-GO', name: 'Goa'},
  {order: 325, level: 4, twdgCode: 'IND-GU', name: 'Gujarat'},
  {order: 326, level: 4, twdgCode: 'IND-HA', name: 'Haryana'},
  {order: 327, level: 4, twdgCode: 'IND-JK', name: 'Jharkhand'},
  {order: 328, level: 4, twdgCode: 'IND-KE', name: 'Kerala'},
  {order: 329, level: 4, twdgCode: 'IND-KL', name: 'Karaikal'},
  {order: 330, level: 4, twdgCode: 'IND-KT', name: 'Karnataka'},
  {order: 331, level: 4, twdgCode: 'IND-MH', name: 'Mahe'},
  {order: 332, level: 4, twdgCode: 'IND-MP', name: 'Madhya Pradesh'},
  {order: 333, level: 4, twdgCode: 'IND-MR', name: 'Maharashtra'},
  {order: 334, level: 4, twdgCode: 'IND-OR', name: 'Orissa'},
  {order: 335, level: 4, twdgCode: 'IND-PO', name: 'Pondicherry'},
  {order: 336, level: 4, twdgCode: 'IND-PU', name: 'Punjab'},
  {order: 337, level: 4, twdgCode: 'IND-RA', name: 'Rajasthan'},
  {order: 338, level: 4, twdgCode: 'IND-TN', name: 'Tamil Nadu'},
  {order: 339, level: 4, twdgCode: 'IND-UP', name: 'Uttar Pradesh'},
  {order: 340, level: 4, twdgCode: 'IND-WB', name: 'West Bengal'},
  {order: 341, level: 4, twdgCode: 'IND-YA', name: 'Yanam'},
  {order: 342, level: 3, twdgCode: 'LDV', name: 'Laccadive Is.'},
  {order: 343, level: 3, twdgCode: 'MDV', name: 'Maldives'},
  {order: 344, level: 3, twdgCode: 'NEP', name: 'Nepal'},
  {order: 345, level: 3, twdgCode: 'PAK', name: 'Pakistan'},
  {order: 346, level: 3, twdgCode: 'SRL', name: 'Sri Lanka'},
  {order: 347, level: 3, twdgCode: 'WHM', name: 'West Himalaya'},
  {order: 348, level: 4, twdgCode: 'WHM-HP', name: 'Himachal Pradesh'},
  {order: 349, level: 4, twdgCode: 'WHM-JK', name: 'Jammu-Kashmir'},
  {order: 350, level: 4, twdgCode: 'WHM-UT', name: 'Uttaranchal'},
  {order: 351, level: 2, twdgCode: '41', name: 'Indo-China'},
  {order: 352, level: 3, twdgCode: 'AND', name: 'Andaman Is.'},
  {order: 353, level: 4, twdgCode: 'AND-AN', name: 'Andaman Is.'},
  {order: 354, level: 4, twdgCode: 'AND-CO', name: 'Coco Is.'},
  {order: 355, level: 3, twdgCode: 'CBD', name: 'Cambodia'},
  {order: 356, level: 3, twdgCode: 'LAO', name: 'Laos'},
  {order: 357, level: 3, twdgCode: 'MYA', name: 'Myanmar'},
  {order: 358, level: 3, twdgCode: 'NCB', name: 'Nicobar Is.'},
  {order: 359, level: 3, twdgCode: 'SCS', name: 'South China Sea'},
  {order: 360, level: 4, twdgCode: 'SCS-PI', name: 'Paracel Is.'},
  {order: 361, level: 4, twdgCode: 'SCS-SI', name: 'Spratly Is.'},
  {order: 362, level: 3, twdgCode: 'THA', name: 'Thailand'},
  {order: 363, level: 3, twdgCode: 'VIE', name: 'Vietnam'},
  {order: 364, level: 2, twdgCode: '42', name: 'Malesia'},
  {order: 365, level: 3, twdgCode: 'BOR', name: 'Borneo'},
  {order: 366, level: 4, twdgCode: 'BOR-BR', name: 'Brunei'},
  {order: 367, level: 4, twdgCode: 'BOR-KA', name: 'Kalimantan'},
  {order: 368, level: 4, twdgCode: 'BOR-SB', name: 'Sabah'},
  {order: 369, level: 4, twdgCode: 'BOR-SR', name: 'Sarawak'},
  {order: 370, level: 3, twdgCode: 'CKI', name: 'Cocos (Keeling) Is.'},
  {order: 371, level: 3, twdgCode: 'JAW', name: 'Jawa'},
  {order: 372, level: 3, twdgCode: 'LSI', name: 'Lesser Sunda Is.'},
  {order: 373, level: 4, twdgCode: 'LSI-BA', name: 'Bali'},
  {order: 374, level: 4, twdgCode: 'LSI-ET', name: 'East Timor'},
  {order: 375, level: 4, twdgCode: 'LSI-LS', name: 'Lesser Sunda Is.'},
  {order: 376, level: 3, twdgCode: 'MLY', name: 'Malaya'},
  {order: 377, level: 4, twdgCode: 'MLY-PM', name: 'Peninsular Malaysia'},
  {order: 378, level: 4, twdgCode: 'MLY-SI', name: 'Singapore'},
  {order: 379, level: 3, twdgCode: 'MOL', name: 'Maluku'},
  {order: 380, level: 3, twdgCode: 'PHI', name: 'Philippines'},
  {order: 381, level: 3, twdgCode: 'SUL', name: 'Sulawesi'},
  {order: 382, level: 3, twdgCode: 'SUM', name: 'Sumatera'},
  {order: 383, level: 3, twdgCode: 'XMS', name: 'Christmas I.'},
  {order: 384, level: 2, twdgCode: '43', name: 'Papuasia'},
  {order: 385, level: 3, twdgCode: 'BIS', name: 'Bismarck Archipelago'},
  {order: 386, level: 3, twdgCode: 'NWG', name: 'New Guinea'},
  {order: 387, level: 4, twdgCode: 'NWG-PN', name: 'Papua New Guinea'},
  {order: 388, level: 4, twdgCode: 'NWG-IJ', name: 'Irian Jaya'},
  {order: 389, level: 3, twdgCode: 'SOL', name: 'Solomon Is.'},
  {order: 390, level: 4, twdgCode: 'SOL-NO', name: 'North Solomons'},
  {order: 391, level: 4, twdgCode: 'SOL-SO', name: 'South Solomons'},
  {order: 392, level: 1, twdgCode: '5', name: 'Australasia'},
  {order: 393, level: 2, twdgCode: '50', name: 'Australia'},
  {order: 394, level: 3, twdgCode: 'NFK', name: 'Norfolk Is.'},
  {order: 395, level: 4, twdgCode: 'NFK-LH', name: 'Lord Howe I.'},
  {order: 396, level: 4, twdgCode: 'NFK-NI', name: 'Norfolk I.'},
  {order: 397, level: 3, twdgCode: 'NSW', name: 'New South Wales'},
  {
    order: 398,
    level: 4,
    twdgCode: 'NSW-CT',
    name: 'Australian Capital Territory'
  },
  {order: 399, level: 4, twdgCode: 'NSW-NS', name: 'New South Wales'},
  {order: 400, level: 3, twdgCode: 'NTA', name: 'Northern Territory'},
  {order: 401, level: 3, twdgCode: 'QLD', name: 'Queensland'},
  {order: 402, level: 4, twdgCode: 'QLD-CS', name: 'Coral Sea Is. Territory'},
  {order: 403, level: 4, twdgCode: 'QLD-QU', name: 'Queensland'},
  {order: 404, level: 3, twdgCode: 'SOA', name: 'South Australia'},
  {order: 405, level: 3, twdgCode: 'TAS', name: 'Tasmania'},
  {order: 406, level: 3, twdgCode: 'VIC', name: 'Victoria'},
  {order: 407, level: 3, twdgCode: 'WAU', name: 'Western Australia'},
  {order: 408, level: 4, twdgCode: 'WAU-AC', name: 'Ashmore-Cartier Is.'},
  {order: 409, level: 4, twdgCode: 'WAU-WA', name: 'Western Australia'},
  {order: 410, level: 2, twdgCode: '51', name: 'New Zealand'},
  {order: 411, level: 3, twdgCode: 'ATP', name: 'Antipodean Is.'},
  {order: 412, level: 3, twdgCode: 'CTM', name: 'Chatham Is.'},
  {order: 413, level: 3, twdgCode: 'KER', name: 'Kermadec Is.'},
  {order: 414, level: 3, twdgCode: 'NZN', name: 'New Zealand North'},
  {order: 415, level: 3, twdgCode: 'NZS', name: 'New Zealand South'},
  {order: 416, level: 1, twdgCode: '6', name: 'Pacific'},
  {order: 417, level: 2, twdgCode: '60', name: 'Southwestern Pacific'},
  {order: 418, level: 3, twdgCode: 'FIJ', name: 'Fiji'},
  {order: 419, level: 3, twdgCode: 'GIL', name: 'Gilbert Is.'},
  {order: 420, level: 3, twdgCode: 'HBI', name: 'Howland-Baker Is.'},
  {order: 421, level: 3, twdgCode: 'NRU', name: 'Nauru'},
  {order: 422, level: 3, twdgCode: 'NUE', name: 'Niue'},
  {order: 423, level: 3, twdgCode: 'NWC', name: 'New Caledonia'},
  {order: 424, level: 3, twdgCode: 'PHX', name: 'Phoenix Is.'},
  {order: 425, level: 3, twdgCode: 'SAM', name: 'Samoa'},
  {order: 426, level: 4, twdgCode: 'SAM-AS', name: 'American Samoa'},
  {order: 427, level: 4, twdgCode: 'SAM-WS', name: 'Samoa'},
  {order: 428, level: 3, twdgCode: 'SCZ', name: 'Santa Cruz Is.'},
  {order: 429, level: 3, twdgCode: 'TOK', name: 'Tokelau-Manihiki'},
  {order: 430, level: 4, twdgCode: 'TOK-MA', name: 'Manihiki Is.'},
  {order: 431, level: 4, twdgCode: 'TOK-SW', name: 'Swains I.'},
  {order: 432, level: 4, twdgCode: 'TOK-TO', name: 'Tokelau'},
  {order: 433, level: 3, twdgCode: 'TON', name: 'Tonga'},
  {order: 434, level: 3, twdgCode: 'TUV', name: 'Tuvalu'},
  {order: 435, level: 3, twdgCode: 'VAN', name: 'Vanuatu'},
  {order: 436, level: 3, twdgCode: 'WAL', name: 'Wallis-Futuna Is.'},
  {order: 437, level: 2, twdgCode: '61', name: 'South-Central Pacific'},
  {order: 438, level: 3, twdgCode: 'COO', name: 'Cook Is.'},
  {order: 439, level: 3, twdgCode: 'EAS', name: 'Easter Is.'},
  {order: 440, level: 3, twdgCode: 'LIN', name: 'Line Is.'},
  {order: 441, level: 4, twdgCode: 'LIN-KI', name: 'Kiribati Line Is.'},
  {order: 442, level: 4, twdgCode: 'LIN-US', name: 'U.S. Line Is.'},
  {order: 443, level: 3, twdgCode: 'MRQ', name: 'Marquesas'},
  {order: 444, level: 3, twdgCode: 'PIT', name: 'Pitcairn Is.'},
  {order: 445, level: 3, twdgCode: 'SCI', name: 'Society Is.'},
  {order: 446, level: 3, twdgCode: 'TUA', name: 'Tuamotu'},
  {order: 447, level: 3, twdgCode: 'TUB', name: 'Tubuai Is.'},
  {order: 448, level: 2, twdgCode: '62', name: 'Northwestern Pacific'},
  {order: 449, level: 3, twdgCode: 'CRL', name: 'Caroline Is.'},
  {
    order: 450,
    level: 4,
    twdgCode: 'CRL-MF',
    name: 'Micronesia Federated States'
  },
  {order: 451, level: 4, twdgCode: 'CRL-PA', name: 'Palau'},
  {order: 452, level: 3, twdgCode: 'MCS', name: 'Marcus I.'},
  {order: 453, level: 3, twdgCode: 'MRN', name: 'Marianas'},
  {order: 454, level: 4, twdgCode: 'MRN-GU', name: 'Guam'},
  {order: 455, level: 4, twdgCode: 'MRN-NM', name: 'Northern Marianas'},
  {order: 456, level: 3, twdgCode: 'MRS', name: 'Marshall Is.'},
  {order: 457, level: 3, twdgCode: 'WAK', name: 'Wake I.'},
  {order: 458, level: 2, twdgCode: '63', name: 'North-Central Pacific'},
  {order: 459, level: 3, twdgCode: 'HAW', name: 'Hawaii'},
  {order: 460, level: 4, twdgCode: 'HAW-HI', name: 'Hawaiian Is.'},
  {order: 461, level: 4, twdgCode: 'HAW-JI', name: 'Johnston I.'},
  {order: 462, level: 4, twdgCode: 'HAW-MI', name: 'Midway Is.'},
  {order: 463, level: 1, twdgCode: '7', name: 'Northern America'},
  {order: 464, level: 2, twdgCode: '70', name: 'Subarctic America'},
  {order: 465, level: 3, twdgCode: 'ALU', name: 'Aleutian Is.'},
  {order: 466, level: 3, twdgCode: 'ASK', name: 'Alaska'},
  {order: 467, level: 3, twdgCode: 'GNL', name: 'Greenland'},
  {order: 468, level: 3, twdgCode: 'NUN', name: 'Nunavut'},
  {order: 469, level: 3, twdgCode: 'NWT', name: 'Northwest Territories'},
  {order: 470, level: 3, twdgCode: 'YUK', name: 'Yukon'},
  {order: 471, level: 2, twdgCode: '71', name: 'Western Canada'},
  {order: 472, level: 3, twdgCode: 'ABT', name: 'Alberta'},
  {order: 473, level: 3, twdgCode: 'BRC', name: 'British Columbia'},
  {order: 474, level: 3, twdgCode: 'MAN', name: 'Manitoba'},
  {order: 475, level: 3, twdgCode: 'SAS', name: 'Saskatchewan'},
  {order: 476, level: 2, twdgCode: '72', name: 'Eastern Canada'},
  {order: 477, level: 3, twdgCode: 'LAB', name: 'Labrador'},
  {order: 478, level: 3, twdgCode: 'NBR', name: 'New Brunswick'},
  {order: 479, level: 3, twdgCode: 'NFL', name: 'Newfoundland'},
  {order: 480, level: 4, twdgCode: 'NFL-NE', name: 'Newfoundland'},
  {order: 481, level: 4, twdgCode: 'NFL-SP', name: 'St. Pierre-Miquelon'},
  {order: 482, level: 3, twdgCode: 'NSC', name: 'Nova Scotia'},
  {order: 483, level: 3, twdgCode: 'ONT', name: 'Ontario'},
  {order: 484, level: 3, twdgCode: 'PEI', name: 'Prince Edward I.'},
  {order: 485, level: 3, twdgCode: 'QUE', name: 'Québec'},
  {order: 486, level: 2, twdgCode: '73', name: 'Northwestern U.S.A.'},
  {order: 487, level: 3, twdgCode: 'COL', name: 'Colorado'},
  {order: 488, level: 3, twdgCode: 'IDA', name: 'Idaho'},
  {order: 489, level: 3, twdgCode: 'MNT', name: 'Montana'},
  {order: 490, level: 3, twdgCode: 'ORE', name: 'Oregon'},
  {order: 491, level: 3, twdgCode: 'WAS', name: 'Washington'},
  {order: 492, level: 3, twdgCode: 'WYO', name: 'Wyoming'},
  {order: 493, level: 2, twdgCode: '74', name: 'North-Central U.S.A.'},
  {order: 494, level: 3, twdgCode: 'ILL', name: 'Illinois'},
  {order: 495, level: 3, twdgCode: 'IOW', name: 'Iowa'},
  {order: 496, level: 3, twdgCode: 'KAN', name: 'Kansas'},
  {order: 497, level: 3, twdgCode: 'MIN', name: 'Minnesota'},
  {order: 498, level: 3, twdgCode: 'MSO', name: 'Missouri'},
  {order: 499, level: 3, twdgCode: 'NDA', name: 'North Dakota'},
  {order: 500, level: 3, twdgCode: 'NEB', name: 'Nebraska'},
  {order: 501, level: 3, twdgCode: 'OKL', name: 'Oklahoma'},
  {order: 502, level: 3, twdgCode: 'SDA', name: 'South Dakota'},
  {order: 503, level: 3, twdgCode: 'WIS', name: 'Wisconsin'},
  {order: 504, level: 2, twdgCode: '75', name: 'Northeastern U.S.A.'},
  {order: 505, level: 3, twdgCode: 'CNT', name: 'Connecticut'},
  {order: 506, level: 3, twdgCode: 'INI', name: 'Indiana'},
  {order: 507, level: 3, twdgCode: 'MAI', name: 'Maine'},
  {order: 508, level: 3, twdgCode: 'MAS', name: 'Massachusetts'},
  {order: 509, level: 3, twdgCode: 'MIC', name: 'Michigan'},
  {order: 510, level: 3, twdgCode: 'NWH', name: 'New Hampshire'},
  {order: 511, level: 3, twdgCode: 'NWJ', name: 'New Jersey'},
  {order: 512, level: 3, twdgCode: 'NWY', name: 'New York'},
  {order: 513, level: 3, twdgCode: 'OHI', name: 'Ohio'},
  {order: 514, level: 3, twdgCode: 'PEN', name: 'Pennsylvania'},
  {order: 515, level: 3, twdgCode: 'RHO', name: 'Rhode I.'},
  {order: 516, level: 3, twdgCode: 'VER', name: 'Vermont'},
  {order: 517, level: 3, twdgCode: 'WVA', name: 'West Virginia'},
  {order: 518, level: 2, twdgCode: '76', name: 'Southwestern U.S.A.'},
  {order: 519, level: 3, twdgCode: 'ARI', name: 'Arizona'},
  {order: 520, level: 3, twdgCode: 'CAL', name: 'California'},
  {order: 521, level: 3, twdgCode: 'NEV', name: 'Nevada'},
  {order: 522, level: 3, twdgCode: 'UTA', name: 'Utah'},
  {order: 523, level: 2, twdgCode: '77', name: 'South-Central U.S.A.'},
  {order: 524, level: 3, twdgCode: 'NWM', name: 'New Mexico'},
  {order: 525, level: 3, twdgCode: 'TEX', name: 'Texas'},
  {order: 526, level: 2, twdgCode: '78', name: 'Southeastern U.S.A.'},
  {order: 527, level: 3, twdgCode: 'ALA', name: 'Alabama'},
  {order: 528, level: 3, twdgCode: 'ARK', name: 'Arkansas'},
  {order: 529, level: 3, twdgCode: 'DEL', name: 'Delaware'},
  {order: 530, level: 3, twdgCode: 'FLA', name: 'Florida'},
  {order: 531, level: 3, twdgCode: 'GEO', name: 'Georgia'},
  {order: 532, level: 3, twdgCode: 'KTY', name: 'Kentucky'},
  {order: 533, level: 3, twdgCode: 'LOU', name: 'Louisiana'},
  {order: 534, level: 3, twdgCode: 'MRY', name: 'Maryland'},
  {order: 535, level: 3, twdgCode: 'MSI', name: 'Mississippi'},
  {order: 536, level: 3, twdgCode: 'NCA', name: 'North Carolina'},
  {order: 537, level: 3, twdgCode: 'SCA', name: 'South Carolina'},
  {order: 538, level: 3, twdgCode: 'TEN', name: 'Tennessee'},
  {order: 539, level: 3, twdgCode: 'VRG', name: 'Virginia'},
  {order: 540, level: 3, twdgCode: 'WDC', name: 'District of Columbia'},
  {order: 541, level: 2, twdgCode: '79', name: 'Mexico'},
  {order: 542, level: 3, twdgCode: 'MXC', name: 'Mexico Central'},
  {order: 543, level: 4, twdgCode: 'MXC-DF', name: 'Mexico Distrito Federal'},
  {order: 544, level: 4, twdgCode: 'MXC-ME', name: 'Mexico State'},
  {order: 545, level: 4, twdgCode: 'MXC-MO', name: 'Morelos'},
  {order: 546, level: 4, twdgCode: 'MXC-PU', name: 'Puebla'},
  {order: 547, level: 4, twdgCode: 'MXC-TL', name: 'Tlaxcala'},
  {order: 548, level: 3, twdgCode: 'MXE', name: 'Mexico Northeast'},
  {order: 549, level: 4, twdgCode: 'MXE-AG', name: 'Aguascalientes'},
  {order: 550, level: 4, twdgCode: 'MXE-CO', name: 'Coahuila'},
  {order: 551, level: 4, twdgCode: 'MXE-CU', name: 'Chihuahua'},
  {order: 552, level: 4, twdgCode: 'MXE-DU', name: 'Durango'},
  {order: 553, level: 4, twdgCode: 'MXE-GU', name: 'Guanajuato'},
  {order: 554, level: 4, twdgCode: 'MXE-HI', name: 'Hidalgo'},
  {order: 555, level: 4, twdgCode: 'MXE-NL', name: 'Nuevo León'},
  {order: 556, level: 4, twdgCode: 'MXE-QU', name: 'Querétaro'},
  {order: 557, level: 4, twdgCode: 'MXE-SL', name: 'San Luis Potosí'},
  {order: 558, level: 4, twdgCode: 'MXE-TA', name: 'Tamaulipas'},
  {order: 559, level: 4, twdgCode: 'MXE-ZA', name: 'Zacatecas'},
  {order: 560, level: 3, twdgCode: 'MXG', name: 'Mexico Gulf'},
  {order: 561, level: 4, twdgCode: 'MXG-VC', name: 'Veracruz'},
  {order: 562, level: 3, twdgCode: 'MXI', name: 'Mexican Pacific Is.'},
  {order: 563, level: 4, twdgCode: 'MXI-GU', name: 'Guadalupe I.'},
  {order: 564, level: 4, twdgCode: 'MXI-RA', name: 'Rocas Alijos'},
  {order: 565, level: 4, twdgCode: 'MXI-RG', name: 'Revillagigedo Is.'},
  {order: 566, level: 3, twdgCode: 'MXN', name: 'Mexico Northwest'},
  {order: 567, level: 4, twdgCode: 'MXN-BC', name: 'Baja California'},
  {order: 568, level: 4, twdgCode: 'MXN-BS', name: 'Baja California Sur'},
  {order: 569, level: 4, twdgCode: 'MXN-SI', name: 'Sinaloa'},
  {order: 570, level: 4, twdgCode: 'MXN-SO', name: 'Sonora'},
  {order: 571, level: 3, twdgCode: 'MXS', name: 'Mexico Southwest'},
  {order: 572, level: 4, twdgCode: 'MXS-CL', name: 'Colima'},
  {order: 573, level: 4, twdgCode: 'MXS-GR', name: 'Guerrero'},
  {order: 574, level: 4, twdgCode: 'MXS-JA', name: 'Jalisco'},
  {order: 575, level: 4, twdgCode: 'MXS-MI', name: 'Michoacan'},
  {order: 576, level: 4, twdgCode: 'MXS-NA', name: 'Nayarit'},
  {order: 577, level: 4, twdgCode: 'MXS-OA', name: 'Oaxaca'},
  {order: 578, level: 3, twdgCode: 'MXT', name: 'Mexico Southeast'},
  {order: 579, level: 4, twdgCode: 'MXT-CA', name: 'Campeche'},
  {order: 580, level: 4, twdgCode: 'MXT-CI', name: 'Chiapas'},
  {order: 581, level: 4, twdgCode: 'MXT-QR', name: 'Quintana Roo'},
  {order: 582, level: 4, twdgCode: 'MXT-TB', name: 'Tabasco'},
  {order: 583, level: 4, twdgCode: 'MXT-YU', name: 'Yucatán'},
  {order: 584, level: 1, twdgCode: '8', name: 'Southern America'},
  {order: 585, level: 2, twdgCode: '80', name: 'Central America'},
  {order: 586, level: 3, twdgCode: 'BLZ', name: 'Belize'},
  {order: 587, level: 3, twdgCode: 'COS', name: 'Costa Rica'},
  {order: 588, level: 3, twdgCode: 'CPI', name: 'Central American Pacific Is.'},
  {order: 589, level: 4, twdgCode: 'CPI-CL', name: 'Clipperton I.'},
  {order: 590, level: 4, twdgCode: 'CPI-CO', name: 'Cocos I.'},
  {order: 591, level: 4, twdgCode: 'CPI-MA', name: 'Malpelo I.'},
  {order: 592, level: 3, twdgCode: 'ELS', name: 'El Salvador'},
  {order: 593, level: 3, twdgCode: 'GUA', name: 'Guatemala'},
  {order: 594, level: 3, twdgCode: 'HON', name: 'Honduras'},
  {order: 595, level: 3, twdgCode: 'NIC', name: 'Nicaragua'},
  {order: 596, level: 3, twdgCode: 'PAN', name: 'Panama'},
  {order: 597, level: 2, twdgCode: '81', name: 'Caribbean'},
  {order: 598, level: 3, twdgCode: 'ARU', name: 'Aruba'},
  {order: 599, level: 3, twdgCode: 'BAH', name: 'Bahamas'},
  {order: 600, level: 3, twdgCode: 'BER', name: 'Bermuda'},
  {order: 601, level: 3, twdgCode: 'CAY', name: 'Cayman Is.'},
  {order: 602, level: 3, twdgCode: 'CUB', name: 'Cuba'},
  {order: 603, level: 3, twdgCode: 'DOM', name: 'Dominican Republic'},
  {order: 604, level: 3, twdgCode: 'HAI', name: 'Haiti'},
  {order: 605, level: 4, twdgCode: 'HAI-HA', name: 'Haiti'},
  {order: 606, level: 4, twdgCode: 'HAI-NI', name: 'Navassa I.'},
  {order: 607, level: 3, twdgCode: 'JAM', name: 'Jamaica'},
  {order: 608, level: 3, twdgCode: 'LEE', name: 'Leeward Is.'},
  {order: 609, level: 4, twdgCode: 'LEE-AB', name: 'Antigua-Barbuda'},
  {order: 610, level: 4, twdgCode: 'LEE-AG', name: 'Anguilla'},
  {order: 611, level: 4, twdgCode: 'LEE-AV', name: 'Aves I.'},
  {order: 612, level: 4, twdgCode: 'LEE-BV', name: 'British Virgin Is.'},
  {order: 613, level: 4, twdgCode: 'LEE-GU', name: 'Guadeloupe'},
  {order: 614, level: 4, twdgCode: 'LEE-MO', name: 'Montserrat'},
  {order: 615, level: 4, twdgCode: 'LEE-NL', name: 'Netherlands Leeward Is.'},
  {order: 616, level: 4, twdgCode: 'LEE-SK', name: 'St. Kitts-Nevis'},
  {order: 617, level: 4, twdgCode: 'LEE-SM', name: 'St. Martin-St. Barthelemy'},
  {order: 618, level: 4, twdgCode: 'LEE-VI', name: 'Virgin Is.'},
  {order: 619, level: 3, twdgCode: 'NLA', name: 'Netherlands Antilles'},
  {order: 620, level: 4, twdgCode: 'NLA-BO', name: 'Bonaire'},
  {order: 621, level: 4, twdgCode: 'NLA-CU', name: 'Curaçao'},
  {order: 622, level: 3, twdgCode: 'PUE', name: 'Puerto Rico'},
  {order: 623, level: 3, twdgCode: 'SWC', name: 'Southwest Caribbean'},
  {order: 624, level: 4, twdgCode: 'SWC-CC', name: 'Colombian Caribbean Is.'},
  {order: 625, level: 4, twdgCode: 'SWC-HC', name: 'Honduran Caribbean Is.'},
  {order: 626, level: 4, twdgCode: 'SWC-NC', name: 'Nicaraguan Caribbean Is.'},
  {order: 627, level: 3, twdgCode: 'TCI', name: 'Turks-Caicos Is.'},
  {order: 628, level: 3, twdgCode: 'TRT', name: 'Trinidad-Tobago'},
  {order: 629, level: 3, twdgCode: 'VNA', name: 'Venezuelan Antilles'},
  {order: 630, level: 3, twdgCode: 'WIN', name: 'Windward Is.'},
  {order: 631, level: 4, twdgCode: 'WIN-BA', name: 'Barbados'},
  {order: 632, level: 4, twdgCode: 'WIN-DO', name: 'Dominica'},
  {order: 633, level: 4, twdgCode: 'WIN-GR', name: 'Grenada'},
  {order: 634, level: 4, twdgCode: 'WIN-MA', name: 'Martinique'},
  {order: 635, level: 4, twdgCode: 'WIN-SL', name: 'St. Lucia'},
  {order: 636, level: 4, twdgCode: 'WIN-SV', name: 'St. Vincent'},
  {order: 637, level: 2, twdgCode: '82', name: 'Northern South America'},
  {order: 638, level: 3, twdgCode: 'FRG', name: 'French Guiana'},
  {order: 639, level: 3, twdgCode: 'GUY', name: 'Guyana'},
  {order: 640, level: 3, twdgCode: 'SUR', name: 'Suriname'},
  {order: 641, level: 3, twdgCode: 'VEN', name: 'Venezuela'},
  {order: 642, level: 2, twdgCode: '83', name: 'Western South America'},
  {order: 643, level: 3, twdgCode: 'BOL', name: 'Bolivia'},
  {order: 644, level: 3, twdgCode: 'CLM', name: 'Colombia'},
  {order: 645, level: 3, twdgCode: 'ECU', name: 'Ecuador'},
  {order: 646, level: 3, twdgCode: 'GAL', name: 'Galápagos'},
  {order: 647, level: 3, twdgCode: 'PER', name: 'Peru'},
  {order: 648, level: 2, twdgCode: '84', name: 'Brazil'},
  {order: 649, level: 3, twdgCode: 'BZC', name: 'Brazil West-Central'},
  {order: 650, level: 4, twdgCode: 'BZC-DF', name: 'Brasilia Distrito Federal'},
  {order: 651, level: 4, twdgCode: 'BZC-GO', name: 'Goias'},
  {order: 652, level: 4, twdgCode: 'BZC-MS', name: 'Mato Grosso do Sul'},
  {order: 653, level: 4, twdgCode: 'BZC-MT', name: 'Mato Grosso'},
  {order: 654, level: 3, twdgCode: 'BZE', name: 'Brazil Northeast'},
  {order: 655, level: 4, twdgCode: 'BZE-AL', name: 'Alagoas'},
  {order: 656, level: 4, twdgCode: 'BZE-BA', name: 'Bahia'},
  {order: 657, level: 4, twdgCode: 'BZE-CE', name: 'Ceara'},
  {order: 658, level: 4, twdgCode: 'BZE-FN', name: 'Fernando de Noronha'},
  {order: 659, level: 4, twdgCode: 'BZE-MA', name: 'Maranhao'},
  {order: 660, level: 4, twdgCode: 'BZE-PB', name: 'Paraiba'},
  {order: 661, level: 4, twdgCode: 'BZE-PE', name: 'Pernambuco'},
  {order: 662, level: 4, twdgCode: 'BZE-PI', name: 'Piaui'},
  {order: 663, level: 4, twdgCode: 'BZE-RN', name: 'Rio Grande do Norte'},
  {order: 664, level: 4, twdgCode: 'BZE-SE', name: 'Sergipe'},
  {order: 665, level: 3, twdgCode: 'BZL', name: 'Brazil Southeast'},
  {order: 666, level: 4, twdgCode: 'BZL-ES', name: 'Espirito Santo'},
  {order: 667, level: 4, twdgCode: 'BZL-MG', name: 'Minas Gerais'},
  {order: 668, level: 4, twdgCode: 'BZL-RJ', name: 'Rio de Janeiro'},
  {order: 669, level: 4, twdgCode: 'BZL-SP', name: 'Sao Paulo'},
  {order: 670, level: 4, twdgCode: 'BZL-TR', name: 'Trindade'},
  {order: 671, level: 3, twdgCode: 'BZN', name: 'Brazil North'},
  {order: 672, level: 4, twdgCode: 'BZN-AC', name: 'Acre'},
  {order: 673, level: 4, twdgCode: 'BZN-AM', name: 'Amazonas'},
  {order: 674, level: 4, twdgCode: 'BZN-AP', name: 'Amapa'},
  {order: 675, level: 4, twdgCode: 'BZN-PA', name: 'Para'},
  {order: 676, level: 4, twdgCode: 'BZN-RM', name: 'Roraima'},
  {order: 677, level: 4, twdgCode: 'BZN-RO', name: 'Rondonia'},
  {order: 678, level: 4, twdgCode: 'BZN-TO', name: 'Tocantins'},
  {order: 679, level: 3, twdgCode: 'BZS', name: 'Brazil South'},
  {order: 680, level: 4, twdgCode: 'BZS-PR', name: 'Parana'},
  {order: 681, level: 4, twdgCode: 'BZS-RS', name: 'Rio Grande do Sul'},
  {order: 682, level: 4, twdgCode: 'BZS-SC', name: 'Santa Catarina'},
  {order: 683, level: 2, twdgCode: '85', name: 'Southern South America'},
  {order: 684, level: 3, twdgCode: 'AGE', name: 'Argentina Northeast'},
  {order: 685, level: 4, twdgCode: 'AGE-BA', name: 'Buenos Aires'},
  {order: 686, level: 4, twdgCode: 'AGE-CD', name: 'Cordoba'},
  {order: 687, level: 4, twdgCode: 'AGE-CH', name: 'Chaco'},
  {order: 688, level: 4, twdgCode: 'AGE-CN', name: 'Corrientes'},
  {
    order: 689,
    level: 4,
    twdgCode: 'AGE-DF',
    name: 'Argentina Distrito Federal'
  },
  {order: 690, level: 4, twdgCode: 'AGE-ER', name: 'Entre Rios'},
  {order: 691, level: 4, twdgCode: 'AGE-FO', name: 'Formosa'},
  {order: 692, level: 4, twdgCode: 'AGE-LP', name: 'La Pampa'},
  {order: 693, level: 4, twdgCode: 'AGE-MI', name: 'Misiones'},
  {order: 694, level: 4, twdgCode: 'AGE-SF', name: 'Santa Fe'},
  {order: 695, level: 3, twdgCode: 'AGS', name: 'Argentina South'},
  {order: 696, level: 4, twdgCode: 'AGS-CB', name: 'Chubut'},
  {order: 697, level: 4, twdgCode: 'AGS-NE', name: 'Neuquen'},
  {order: 698, level: 4, twdgCode: 'AGS-RN', name: 'Rio Negro'},
  {order: 699, level: 4, twdgCode: 'AGS-SC', name: 'Santa Cruz'},
  {
    order: 700,
    level: 4,
    twdgCode: 'AGS-TF',
    name: 'Tierra del Fuego (Argentina)'
  },
  {order: 701, level: 3, twdgCode: 'AGW', name: 'Argentina Northwest'},
  {order: 702, level: 4, twdgCode: 'AGW-CA', name: 'Catamarca'},
  {order: 703, level: 4, twdgCode: 'AGW-JU', name: 'Jujuy'},
  {order: 704, level: 4, twdgCode: 'AGW-LR', name: 'La Rioja'},
  {order: 705, level: 4, twdgCode: 'AGW-ME', name: 'Mendoza'},
  {order: 706, level: 4, twdgCode: 'AGW-SA', name: 'Salta'},
  {order: 707, level: 4, twdgCode: 'AGW-SE', name: 'Santiago del Estero'},
  {order: 708, level: 4, twdgCode: 'AGW-SJ', name: 'San Juan'},
  {order: 709, level: 4, twdgCode: 'AGW-SL', name: 'San Luis'},
  {order: 710, level: 4, twdgCode: 'AGW-TU', name: 'Tucuman'},
  {order: 711, level: 3, twdgCode: 'CLC', name: 'Chile Central'},
  {order: 712, level: 4, twdgCode: 'CLC-BI', name: 'Biobio'},
  {order: 713, level: 4, twdgCode: 'CLC-CO', name: 'Coquimbo'},
  {order: 714, level: 4, twdgCode: 'CLC-LA', name: 'La Araucania'},
  {order: 715, level: 4, twdgCode: 'CLC-MA', name: 'Maule'},
  {order: 716, level: 4, twdgCode: 'CLC-OH', name: "O'Higgins"},
  {order: 717, level: 4, twdgCode: 'CLC-SA', name: 'Santiago'},
  {order: 718, level: 4, twdgCode: 'CLC-VA', name: 'Valparaiso'},
  {order: 719, level: 3, twdgCode: 'CLN', name: 'Chile North'},
  {order: 720, level: 4, twdgCode: 'CLN-AN', name: 'Antofagasta'},
  {order: 721, level: 4, twdgCode: 'CLN-AT', name: 'Atacama'},
  {order: 722, level: 4, twdgCode: 'CLN-TA', name: 'Tarapaca'},
  {order: 723, level: 3, twdgCode: 'CLS', name: 'Chile South'},
  {order: 724, level: 4, twdgCode: 'CLS-AI', name: 'Aisen'},
  {order: 725, level: 4, twdgCode: 'CLS-LL', name: 'Los Lagos'},
  {order: 726, level: 4, twdgCode: 'CLS-MG', name: 'Magellanes'},
  {order: 727, level: 3, twdgCode: 'DSV', name: 'Desventurados Is.'},
  {order: 728, level: 3, twdgCode: 'JNF', name: 'Juan Fernández Is.'},
  {order: 729, level: 3, twdgCode: 'PAR', name: 'Paraguay'},
  {order: 730, level: 3, twdgCode: 'URU', name: 'Uruguay'},
  {order: 731, level: 1, twdgCode: '9', name: 'Antarctic'},
  {order: 732, level: 2, twdgCode: '90', name: 'Subantarctic Islands'},
  {order: 733, level: 3, twdgCode: 'ASP', name: 'Amsterdam-St.Paul Is.'},
  {order: 734, level: 3, twdgCode: 'BOU', name: 'Bouvet I.'},
  {order: 735, level: 3, twdgCode: 'CRZ', name: 'Crozet Is.'},
  {order: 736, level: 3, twdgCode: 'FAL', name: 'Falkland Is.'},
  {order: 737, level: 3, twdgCode: 'HMD', name: 'Heard-McDonald Is.'},
  {order: 738, level: 3, twdgCode: 'KEG', name: 'Kerguelen'},
  {order: 739, level: 3, twdgCode: 'MAQ', name: 'Macquarie Is.'},
  {order: 740, level: 3, twdgCode: 'MPE', name: 'Marion-Prince Edward Is.'},
  {order: 741, level: 3, twdgCode: 'SGE', name: 'South Georgia'},
  {order: 742, level: 3, twdgCode: 'SSA', name: 'South Sandwich Is.'},
  {order: 743, level: 3, twdgCode: 'TDC', name: 'Tristan da Cunha'},
  {order: 744, level: 2, twdgCode: '91', name: 'Antarctic Continent'},
  {order: 745, level: 3, twdgCode: 'ANT', name: 'Antarctica'}
]

const zones = nonFilteredZones.filter(
  (v, i, a) => a.findIndex(t => t.name === v.name && t.name === v.name) === i
)

module.exports = zones
